### PR TITLE
Fix signTypeData v1 verify failure.

### PR DESCRIPTION
**Pull request by sherardxu**
#344

### CODE REVIEW

**Comment by hewigovens** [comment]
I think you need to change the sample iOS or Android app?

**Comment by sherardxu** [comment]
No, `signTypedMessage` works fine.

**Comment by hewigovens** [comment]
We may need to implement legacy eip712 in wallet core before merging this

**Comment by sherardxu** [comment]
As far as I know `SignTypedDataVersion V1 V3 V4` have the same signing process.

code from [MetaMask/eth-sig-util](https://github.com/MetaMask/eth-sig-util/blob/d1f01ba799de734d84cdf599d19a215f8fecb5b2/src/sign-typed-data.ts#L529).

```
const messageHash =
    version === SignTypedDataVersion.V1
      ? _typedSignatureHash(data as TypedDataV1)
      : TypedDataUtils.eip712Hash(
          data as TypedMessage<T>,
          version as SignTypedDataVersion.V3 | SignTypedDataVersion.V4,
        );
const sig = ecsign(messageHash, privateKey);
```

I have tested the android sample of this repo and it works fine.  [(View Results)](https://user-images.githubusercontent.com/5781503/203459769-785eb565-e52b-4918-b5d3-db195e7b45c3.png)

So I don't think you need to change wallet core.

**Pull request closed without merging**
