### PR TITLE
fix: call _request with wrong wrapResult within sendAsync

### PR DESCRIPTION
**Pull request by ibufu**
**Problem:**
```js
Promise.all(payload.map(that._request.bind(that)))
```
When using the above code, it calls `_request` with a wrong wrapResult, the index of the payload.

### CODE REVIEW

**Comment by hewigovens** [comment]
@ibufu could you please revert `trust-min.js` change and add some test somehow?

**Comment by ibufu** [comment]
Yes

**Comment by ibufu** [comment]
@hewigovens done

**Review by hewigovens — APPROVED** [review]
Will the test returns different values later? it looks like it sends real network requests

**Comment by ibufu** [comment]
> Will the test returns different values later? it looks like it sends real network requests

I think it won't. It called BUSD's name and decimals.

**Comment by 09168806659** [comment]
[Node CI](https://github.com/trustwallet/trust-web3-provider/actions/workflows/ci.yml)

**Pull request merged**
