### PR TITLE
upgrade provider-engine

### PR DESCRIPTION
**Pull request by mishfit**
- [x] upgrade provider engine to diagnose issues
- [x] reverse engineer https://manager.0xcert.org/ to diagnose issues
- [x] upgrade engine

### CODE REVIEW

**Comment by hewigovens** [comment]
Does this fix issue #3 as well?

**Comment by mishfit** [comment]
@hewigovens yes. Everyone's keen to start using web3 1.0 (it's still in beta!). Mist doesn't support it yet (it's been developed, but not released yet).

It's slow going because supporting one breaks something in the other, I'm pretty close though.

**Comment by vikmeup** [comment]
@mishfit do we still need this PR?

**Comment by mishfit** [comment]
I think so...I'm still working on a small issue with web3 1.0 (though I have added tests, I just haven't wried them up to travis ci yet)

**Comment by mishfit** [comment]
@vikmeup this passes the tests when you run them locally,

It would be trivial to add them to Travis CI

It doesn't solve the problem for https://github.com/TrustWallet/trust-web3-provider/issues/6 but it might solve the problem for https://github.com/TrustWallet/trust-wallet-ios/issues/742

**Pull request merged**
