### PR TITLE
Add Solana support

### PR DESCRIPTION
**Pull request by rsrbk**
- [x] Scaffold auto reconnect
- [x] signMessage
- [x] signAndSendTransaction - return tx hash (sent by the app)
- [x] signAllTransactions - return signed tx
- [ ] Add it to solana adapter repo
- [x] Remove all "FIXME" in the code
- [x] refactor `config` 

```json
{
  "ethereum": {
    "chainId": 0,
    "rpcUrl": "https://",
    "isMetaMask": false
  },
  "solana": {
    "cluster": "mainnet-beta"
  },
  "isDebug": false
}
```

### CODE REVIEW

**Comment by rsrbk** [comment]
Ready for review

**Review by hewigovens — APPROVED** [review]
🚀🚀

**Review by ArtemGoryunov — APPROVED** [review]

**Comment by trastvolt** [comment]
rsrbk/solana

**Comment by trastvolt** [comment]
rsrbk/solana

**Pull request merged**
