### PR TITLE
Upload token coin trust wallet 

### PR DESCRIPTION
**Pull request by Kalidkeeyow**

### CODE REVIEW

**Comment by CharlesBlaqk** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Review by Tegimufranka9639 — COMMENTED** [review]
SECURITY.md

**Review by Tegimufranka9639 — COMMENTED** [review]
https://github.com/Tegimufranka9639/fuzzy-funicular/issues/1
Duplicate of #https://link.trustwallet.com/swap?from=c60_t0x6B175474E89094C44Da98b954EedeAC495271d0F&to=c60

**Review by Tegimufranka9639 — COMMENTED** [review]
Kalidkeeyow:masterhttps://link.trustwallet.com/open_coin?asset=c60https://github.com/Tegimufranka9639/fuzzy-funicular/issues/1

**Pull request closed without merging**
