### PR TITLE
Support eth_signTypedData_v4

### PR DESCRIPTION
**Pull request by hewigovens**
Fixes https://github.com/trustwallet/trust-web3-provider/issues/148

### CODE REVIEW

**Review by vikmeup — APPROVED** [review]

**Review by vikmeup — COMMENTED** [review]
Why there is so many additions? 

Screen Shot 2021-05-24 at 9 08 25 AM

**Comment by hewigovens** [comment]
> Why there is so many additions?
> 
> Screen Shot 2021-05-24 at 9 08 25 AM

package-lock.json 🤦‍♂️

**Comment by anxolin** [comment]
Hi! how can I test this PR? I would like to double check if this works with http://cowswap.exchange. It's also compatible with Rinkeby network, to test it easier.

**Comment by hewigovens** [comment]
@anxolin we will release new app version for this support, just tested BAT -> USDC on iOS: https://etherscan.io/tx/0x0735bb2dba93594635ad004b7bb50adce58cf288f998a0107fbb18885e57c5d7

**Review by vikmeup — APPROVED** [review]

**Pull request merged**
